spring:
  application:
    name: coachly-api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.aredegalli.it/realms/coachly-app}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-service
              uri: ${USERS_SERVICE_URI:http://coachly-users-be:8080}
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - RemoveRequestHeader=Cookie
                - UserContextHeaders

            - id: workouts-service
              uri: ${WORKOUTS_SERVICE_URI:http://coachly-workouts-be:8080}
              predicates:
                - Path=/api/workouts/**
              filters:
                - StripPrefix=1
                - RemoveRequestHeader=Cookie
                - UserContextHeaders

            - id: exercises-service
              uri: ${EXERCISES_SERVICE_URI:http://coachly-exercises-be:8080}
              predicates:
                - Path=/api/exercises/**
              filters:
                - StripPrefix=1
                - RemoveRequestHeader=Cookie
                - UserContextHeaders

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

coachly:
  services:
    users:
      url: ${USERS_SERVICE_URI:http://coachly-users-be:8080}
      cache:
        user-id-ttl: 5m
        maximum-size: 10000
